language: "ko-KR"
early_access: false
reviews:
  profile: "balanced"
  request_changes_workflow: true
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - pre-main
path_filters:
  - "!**/*.md"
  - "!**/swagger.json"
  - "!**/*.png"
  - "!**/*.jpg"
tools:
  gitleaks:
    enabled: true
  markdownlint:
    enabled: true
chat:
  auto_reply: true 
