package org.example.sansam.status.domain;

public enum StatusEnum {
    NEW, AVAILABLE, SOLDOUT, SCHEDULED,COMPLETED, ORDER_WAITING, ORDER_PAID,ORDER_ALL_CANCELED,
    ORDER_CANCEL_REQUESTED,
    ORDER_ALL_CANCELED_AND_REVIEW_COMPLETED,ORDER_PARTIAL_CANCELED,
    ORDER_PRODUCT_WAITING, ORDER_PRODUCT_PAID_AND_REVIEW_REQUIRED, ORDER_PRODUCT_PAID_AND_REVIEW_COMPLETED,
    ORDER_PRODUCT_CANCELED,
    CANCEL_COMPLETED, ORDER_PRODUCT_PARTIALLY_CANCELED, CANCEL_REFUNDED,
    ORDER_PRODUCT_REVIEW_REQUIRED,ORDER_PRODUCT_REVIEW_COMPLETED,
    PAYMENT_COMPLETED,PAYMENT_PENDING, PAYMENT_FAILED;
}
