package org.example.sansam.status.domain;

public enum StatusEnum {
    NEW, AVAILABLE, SOLDOUT, SCHEDULED,COMPLETED, ORDER_WAITING, ORDER_PAID,ORDER_ALL_CANCELED,
    ORDER_CANCEL_REQUESTED, ORDER_ALL_CANCELED_AND_REVIEW_REQUIRED,
    ORDER_ALL_CANCELED_AND_REVIEW_COMPLETED,ORDER_PARTIAL_CANCELED,
    ORDER_PRODUCT_WAITING, ORDER_PRODUCT_PAID_AND_REVIEW_REQUIRED, ORDER_PRODUCT_PAID_AND_REVIEW_COMPLETED,
    ORDER_PRODUCT_CANCELED,
    CANCEL_COMPLETED, SOME_PRODUCT_CANCELED;
}
