server:
  port: 8080
  address: 0.0.0.0

  servlet:
    session:
      timeout: 120m
      cookie:
        name: JSESSIONID        # 쿠키 이름
        http-only: true         # JS에서 접근 불가
        secure: false           # https에서만 필요 시 true
        same-site: none
logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.springframework.transaction: ERROR
    org.springframework.orm.jpa.JpaTransactionManager: ERROR
    org.hibernate: ERROR
    org.hibernate.SQL: ERROR

spring:
  thymeleaf:
    encoding: UTF-8
  application:
    name: SanSam
  config:
    activate:
      on-profile: prod

  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=100,expireAfterWrite=24h

  rabbitmq:
    host: localhost
    port: 5672
    username: dev
    password: dev
    template:
      mandatory: true
    publisher-confirm-type: correlated
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 200  #쌓을 수 있는 최대 양인데, 이거 맞나 200개면 500개 버티는데, 200개면 충분하겠지.
        concurrency: 3 #동시에 3개 적당한가...이것도 고민좀 해보고


  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false # 이것도 찾아보세요!!!
  batch:
    jdbc:
      initialize-schema: never   # 앱 실행 시 메타 테이블 자동 생성
    job:
      enabled: false              # 앱 시작할 때 배치 잡 자동 실행하지 않음 (테스트/스케줄러로만 실행)

  mail:
    host: smtp.gmail.com
    port: 587
    username: sansam250721@gmail.com
    password: dgwj cvlz wpqt vfdo         # 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

#    decorator:
#      datasource:
#        p6spy:
#          enable-logging: true
#          multiline: true
#          logging: slf4j
#          tracing:
#            include-parameter-values: true

toss:
  secret-key: ${TOSS_SECRET_KEY}
  confirm-url: ${TOSS_CONFIRM_URL}
  cancel-url: ${TOSS_CANCEL_URL}


management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      probes:
        enabled: true

cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET_NAME}
      custom:
        dir: /images
        defaultUrl: https://your-bucket-name.s3.ap-northeast-2.amazonaws.com/
      path:
        review: reviews
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
cors:
  allowed-origins: http://localhost:3000
websocket:
  allowed-origins: "http://localhost:3000"
