server:
  port: 8080
  address: 0.0.0.0

  servlet:
    session:
      timeout: 120m
      cookie:
        name: JSESSIONID        # 쿠키 이름
        http-only: true         # JS에서 접근 불가
        secure: true           # https에서만 필요 시 true
        same-site: none

spring:
  thymeleaf:
    encoding: UTF-8
  application:
    name: SanSam

  datasource:
    url: jdbc:mysql://sansam.c3240ygmgpix.ap-northeast-2.rds.amazonaws.com:3306/sansam
    username: admin
    password: ordefirenz33!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false # 이것도 찾아보세요!!!

  mail:
    host: smtp.gmail.com
    port: 587
    username: sansam250721@gmail.com
    password: dgwj cvlz wpqt vfdo         # 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

toss:
  secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
  confirm-url: https://api.tosspayments.com/v1/payments/confirm
  cancel-url: https://api.tosspayments.com/v1/payments


management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      probes:
        enabled: true

cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET_NAME}
      custom:
        dir: /images
        defaultUrl: https://your-bucket-name.s3.ap-northeast-2.amazonaws.com/
      path:
        review: reviews
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
cors:
  allowed-origins: >
    https://ordefirenz.shop,
    https://front-end-fawn-pi.vercel.app,
    https://front-end-git-*.vercel.app,
    http://localhost:3000

websocket:
  allowed-origins: >
    https://ordefirenz.shop,
    https://front-end-fawn-pi.vercel.app,
    https://front-end-git-*.vercel.app,
    http://localhost:3000