server:
  port: 8080
  address: 0.0.0.0

  servlet:
    session:
      timeout: 120m
      cookie:
        name: JSESSIONID
        http-only: true
        secure: false
        same-site: none

spring:
  thymeleaf:
    encoding: UTF-8
  application:
    name: SanSam
  profiles:
    default: local  # 기본은 local로
    group:
      prod: prod
      local: local
      test: test

  datasource:
    url: jdbc:mysql://localhost:3305/sansam
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
    open-in-view: false # 이것도 찾아보세요!!!
  batch:
    jdbc:
      initialize-schema: never   # 앱 실행 시 메타 테이블 자동 생성
    job:
      enabled: false              # 앱 시작할 때 배치 잡 자동 실행하지 않음 (테스트/스케줄러로만 실행)

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}    # 앱 비밀번호 (환경변수)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

toss:
  secret-key: ${TOSS_SECRET_KEY}
  confirm-url: ${TOSS_CONFIRM_URL}
  cancel-url: ${TOSS_CANCEL_URL}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: SanSam
  endpoint:
    health:
      probes:
        enabled: true

cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET_NAME}
      custom:
        dir: /images
        defaultUrl: https://${AWS_BUCKET_NAME}.s3.ap-northeast-2.amazonaws.com/
      path:
        review: reviews
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

websocket:
  allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS}
